<?

//$gameID = $argv[1];


$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://www.ladbrokes.com.au/api/1/sport/getEventsByCategoryName");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "token=783475D0-145D-4128-99D6-5AE3DCA3B812&params={\"filter\":{\"name\":\"tennis\"}}");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = "Host: www.ladbrokes.com.au";
$headers[] = "X-Newrelic-Id: UwAGVlRbGwYGV1JWAgM=";
$headers[] = "Cookie: PHPSESSID=v8i2c573scli934h6lhfbdbfd3; _vwo_uuid_v2=0497DA0372BAF2A2CC0FEC928272127A|490acadd5ef9f39031ea0e2fd0578940; __cfduid=dcc47d61d4372c73fb12fe1248c6719d11504326432";
$headers[] = "Accept: */*";
$headers[] = "User-Agent: Ladbrokes/82 (4.9.1) CFNetwork iOS/10.3.2 (iPhone9,3)";
$headers[] = "Accept-Language: en-au";
$headers[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

//var_dump(json_decode($result, true));
$endResult = json_decode($result, true);

$compList = $endResult["result"]["events"];
//var_dump($compList);

$idList = array();

foreach($compList as $item) { //foreach element in $arr
	//Get array of each item
    $idList[] = $item['id'];
    
    //if ($item["title"] == "Istanbul Challenger"){
        getLadDetails($item['id']);
    //}
	
	
}




function getLadDetails($id){

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://www.ladbrokes.com.au/api/1/sport/getMarketsByEventId");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "token=783475D0-145D-4128-99D6-5AE3DCA3B812&params={\"filter\":{\"eventId\":$id}}");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = "Host: www.ladbrokes.com.au";
$headers[] = "X-Newrelic-Id: UwAGVlRbGwYGV1JWAgM=";
$headers[] = "Cookie: PHPSESSID=v8i2c573scli934h6lhfbdbfd3; _vwo_uuid_v2=0497DA0372BAF2A2CC0FEC928272127A|490acadd5ef9f39031ea0e2fd0578940; __cfduid=dcc47d61d4372c73fb12fe1248c6719d11504326432";
$headers[] = "Accept: */*";
$headers[] = "User-Agent: Ladbrokes/82 (4.9.1) CFNetwork iOS/10.3.2 (iPhone9,3)";
$headers[] = "Accept-Language: en-au";
$headers[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

var_dump($result);

// Will dump a beauty json :3
//var_dump(json_decode($result, true));

$endResult = json_decode($result, true);

$player1 = $endResult["result"]["markets"][0]["description"];
$player2 = $endResult["result"]["markets"][1]["description"];
$title = $endResult["result"]["description"];
$startTime = $endResult["result"]["outcomeTime"];
$competition = $endResult["result"]["title"];
$player1Odds = $endResult["result"]["markets"][0]["odds"];
$player2Odds = $endResult["result"]["markets"][1]["odds"];

$servername = "localhost";
$username = "root";
$password = "root";
$dbname = "betting";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} else {



}

//var_dump($endResult["marketList"][0]["outcomeList"][0]["name"]);
$sql = "INSERT INTO tennisLadbrokes (startTime, title, player1, player2, competition, player1Odds, player2Odds) VALUES ('$startTime', '$title', '$player1','$player2', '$competition','$player1Odds', '$player2Odds')";

if ($conn->query($sql) === TRUE) {
                echo "New record created successfully";
            } else {
                echo "Error: user already exists" . "<br>" . $conn->error;
            }



}


return true;

?>
