<?
//All tennis
//$gameID = $argv[1];

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://pubapi.sportsbet.com.au/v1/sportsbook/competitions?classIds=13&detailsLevel=O&flags=FE");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = "Host: pubapi.sportsbet.com.au";
$headers[] = "Accept: application/json";
$headers[] = "Apptoken: F324D1D8-B9CC-4FE1-AE59-7928C72E6719";
$headers[] = "Accept-Language: en-au";
$headers[] = "Content-Type: application/xml";
$headers[] = "Sb-State-Gps: VIC";
$headers[] = "User-Agent: Sportsbet/270 CFNetwork/811.5.4 Darwin/16.6.0";
$headers[] = "Sb-Auth: false";
$headers[] = "Sb-Location: -37.926408,145.345583";
$headers[] = "X-Newrelic-Id: VQcBWFNQGwAJVVZaAgM=";
$headers[] = "Cookie: bm_sv=FA7FE2A80EEC739241DA0F1DD8EC97B8~YmA5yCYY2P+o+cD4pWoOKVvvmVbHz/eT3zWC4hLf8oDxYSiYEIUTAlGEjdvNf9zw/NxlrFMyqnNQL0ZH/5ZIlxUJxLPndd0MwKGtlvFE/o6gIFha4uiRkWvHJVGTP1aX02gHra0IWotmEXNENB1WGQ7489UqTs7tePoawJAlSvA=; ak_bmsc=2B94FE2E48BD802E3A4B9749B50046806847830C54280000C6E7B5596DDE7910~plBczr5urpmAh8KG4QijR4YzhdIQPvvBUyWuS5Rtpu4gA/lkC+bh9kmIIEnWaOQiHrllWVmL2Fbx223FOE44aLmgQ8wkGk4frXxDjvlUNlgXO4ZfI3GbhJ3kcwKN1GiAPfAwoLGmyyoKreDJ8+gik7JKjSlc2J5m9nc9dm1SovV4+g35nlIzVY5Awov4Jnt6s2g5LWT1zB2f/wFYwMoIF3PUqTQuZYvEGnQzn2tsJZAgo=; aid=Sportsbet 17.17; cd18=iPhone9,3; cd2=ios-app; cd34=00000000-0000-0000-0000-000000000000; cd35=N/A; cd9=; uid=";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

$tennisList = json_decode($result, true);

foreach($tennisList["competitionList"] as $item) { //foreach element in $arr
	//Get array of each item
	//$idList[] = $item['id'];
	getEvent($item['id']);
	
}
function getEvent($id){

    //Event List URL
    $url="https://pubapi.sportsbet.com.au/v1/sportsbook/competitions/".$id;
    //  Initiate curl
    $ch = curl_init();
    // Disable SSL verification
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    // Will return the response, if false it print the response
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    // Set the url
    curl_setopt($ch, CURLOPT_URL,$url);
    // Execute
    $result=curl_exec($ch);
    // Closing
    curl_close($ch);

    //var_dump(json_decode($result, true));

    $endResult = json_decode($result, true);

    $compList = $endResult["eventList"];

    $idList = array();

    foreach($compList as $item) { //foreach element in $arr
        //Get array of each item
        $idList[] = $item['id'];
        getDetails($item['id']);
        
    }


}

function getDetails($id){

$url="https://pubapi.sportsbet.com.au/v1/sportsbook/events/".$id;
//  Initiate curl
$ch = curl_init();
// Disable SSL verification
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
// Will return the response, if false it print the response
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
// Set the url
curl_setopt($ch, CURLOPT_URL,$url);
// Execute
$result=curl_exec($ch);
// Closing
curl_close($ch);

// Will dump a beauty json :3
//var_dump(json_decode($result, true));

$endResult = json_decode($result, true);

$player1 = $endResult["marketList"][0]["outcomeList"][0]["name"];
$player2 = $endResult["marketList"][0]["outcomeList"][1]["name"];
$title = $endResult["name"];
$startTime = $endResult["startTime"];
$competition = $endResult["meetingName"];
$player1Odds = $endResult["marketList"][0]["outcomeList"][0]["winPrice"];
$player2Odds = $endResult["marketList"][0]["outcomeList"][1]["winPrice"];
$sportsBetId = $id;

$servername = "localhost";
$username = "root";
$password = "root";
$dbname = "betting";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} else {



}

//var_dump($endResult["marketList"][0]["outcomeList"][0]["name"]);
$sql = "INSERT INTO tennisSportsBet (startTime, title, player1, player2, competition, player1Odds, player2Odds, sportsBetId) VALUES ('$startTime', '$title', '$player1','$player2', '$competition','$player1Odds', '$player2Odds', '$sportsBetId')";

if ($conn->query($sql) === TRUE) {
                echo "New record created successfully";
            } else {
                echo "Error: user already exists" . "<br>" . $conn->error;
            }

echo "\n";
echo "Game ID: " . $endResult["meetingName"];
echo "\n";
echo "\n";
echo "Game Type: " . $endResult["className"];
echo "\n";
echo "\n";
echo "Odds for: ". $endResult["marketList"][0]["outcomeList"][0]["name"];
echo "\n";
echo "Player ID: ". $endResult["marketList"][0]["outcomeList"][0]["outcomeExternalId"];
echo "\n";
echo "Paying: ". $endResult["marketList"][0]["outcomeList"][0]["winPrice"];
echo "\n";
echo "\n";
echo "Odds for: ". $endResult["marketList"][0]["outcomeList"][1]["name"];
echo "\n";
echo "Player ID: ". $endResult["marketList"][0]["outcomeList"][1]["outcomeExternalId"];
echo "\n";
echo "Paying: ". $endResult["marketList"][0]["outcomeList"][1]["winPrice"];
echo "\n";
echo "\n";
echo "-----------------------------------------------------";
echo "\n";


}

return true;

?>